services:
  # Backend API Service
  - type: web
    name: aegis-api
    env: node
    region: ohio
    rootDir: server
    buildCommand: npm ci && npm run build
    startCommand: node build/app.js
    healthCheckPath: /health
    plan: free
    runtime: node
    nodeVersion: 18.x
    port: 10000
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: DOMAIN
        value: https://www.aegistestingtech.com
      - key: CLIENT_URL
        value: https://www.aegistestingtech.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://www.aegistestingtech.com,https://aegistestingtech.com,https://api.aegistestingtech.com
      - key: PORT
        value: "10000"

  # Frontend Service  
  - type: web
    name: aegis-web
    env: static
    buildCommand: cd client/aegis-client && npm ci && npm run build
    staticPublishPath: client/aegis-client/build
    healthCheckPath: /
    envVars:
      - key: REACT_APP_API_URL
        value: https://api.aegistestingtech.com
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
