services:
  # Backend API Service
  - type: web
    name: aegis-api
    env: node
    region: ohio
    rootDir: server
    buildCommand: npm ci && npm run build && chmod +x build/start.sh
    startCommand: cd build && NODE_ENV=production ./start.sh
    healthCheckPath: /health
    plan: free
    runtime: node
    nodeVersion: 18.x
    port: 10000
    envVars:
      - key: MONGO_URI
        sync: true
      - key: JWT_SECRET
        sync: true
      - key: STRIPE_SECRET_KEY
        sync: true
      - key: STRIPE_WEBHOOK_SECRET
        sync: true
      - key: DOMAIN
        value: https://aegistestingtech.com
      - key: CLIENT_URL
        value: https://aegistestingtech.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://www.aegistestingtech.com,https://aegistestingtech.com

  # Frontend Service  
  - type: web
    name: aegis-web
    env: static
    buildCommand: cd client/aegis-client && npm ci && npm run build
    staticPublishPath: client/aegis-client/build
    healthCheckPath: /
    envVars:
      - key: REACT_APP_API_URL
        value: https://aegis-api.onrender.com
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
