services:
  # Backend API Service
  - type: web
    name: aegis-api
    env: node
    region: ohio
    rootDir: server
    buildCommand: |
      chmod +x start.sh
      npm ci
      npm run build
    healthCheckPath: /health
    plan: free
    runtime: node
    nodeVersion: 18.x
    port: 10000
    startCommand: ./start.sh
    buildFilter:
      paths:
        - server/**/*
        - package.json
        - package-lock.json
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Sensitive - must be set manually in Render dashboard
      - key: JWT_SECRET
        sync: false # Sensitive - must be set manually
      - key: STRIPE_SECRET_KEY
        sync: false # Sensitive - must be set manually
      - key: STRIPE_WEBHOOK_SECRET
        sync: false # Sensitive - must be set manually
      - key: DOMAIN
        value: https://www.aegistestingtech.com
      - key: CLIENT_URL
        value: https://www.aegistestingtech.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://www.aegistestingtech.com,https://aegistestingtech.com,https://api.aegistestingtech.com
      - key: PORT
        value: "10000"
    autoDeploy: true
    healthCheckTimeout: 300 # 5 minutes

  # Frontend Service
  - type: web
    name: aegis-web
    env: static
    buildCommand: cd client/aegis-client && npm ci && CI=false GENERATE_SOURCEMAP=false npm run build
    staticPublishPath: client/aegis-client/build
    healthCheckPath: /
    buildFilter:
      paths:
        - client/aegis-client/**/*
        - package.json
        - package-lock.json
    pullRequestPreviewsEnabled: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://api.aegistestingtech.com
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
